version: '3.7'
services:
    app:
        build:
            context: .
            target: base
        env_file: 
            - .env
        depends_on:
            - mongo
        volumes: 
            - /app/node_modules
            - ./:/app 
        ports: 
            - 3000:3000
            - 5000:5000
        command: 
            sh -c 'npm start'    
    mongo:
        image: mongo:latest
        ports:
            - '27017:27017'
    mongo:
        container_name: mongo-container
        image: mongo:latest
        restart: always
        ports: 
            - 27017:27017
        volumes:
            - ./data:/data/db