@startuml
title Data Model

class Album {
    ID : _id
    String Name
    String Artwork
    String Artist
    Song : Song
}

class Playlist {
    ID : _id
    String Name
    String Artwork
    SongList : [Song]
}

class Song {
    ID : _id
    String Title
    String Artwork
    String Artist
    String Track
}

@enduml