@startuml
title Data Model

class Playlist {
    ID : _id
    String Name
    String Description
    SongList : [Song]
}

class Song {
    ID : _id
    String Title
    String Artwork
    String Artist
    String Track
}

@enduml