@startuml

class Album {
    ID : _id
    String Name
    String Artwork
    String Artist
    Song : Song
}

class Song {
    ID : _id
    String Title
    String Artwork
    String Artist
    String Track
}

class Accounts {
    ID : _id
    String Email
    String Hash
}

@enduml